### ISSUE TITLE
graphql-eslint is not working inside a Next.js project

### ISSUE THREAD

**Issue by glenngijsberts** [B2o5T/graphql-eslint#1095] opened 2022-06-20 14:54 UTC
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
> Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

I've been trying to migrate the old graphql plugin to this new `graphql-eslint` parser. It doesn't seem to work for me in my Next.js projects, following the documentation in this repo. I don't think this has anything to do with Next.js itself, but it doesn't seem to work in those projects (including reproduction).

**To Reproduce**

I've created a reproduction [here](https://github.com/glenngijsberts/graphql-eslint-nextjs). Running `yarn lint` will show no errors, however, I'm using a `message` type in the `user.graphql` file, which doesn't exist in my graphql schema. 

**Expected behavior**

I should get ESLint errors.

**Environment:**

- OS: Mac OS
- `@graphql-eslint/eslint-plugin`: 3.10.4
- Node.js: 16.12.0

**Additional context**

Tried to use different options, such as a graphql schema in json format, my queries in `js` format but nothing seemed to work.

**Comment by B2o5T** [comment] 2022-06-20 22:36
Hi @glenngijsberts, thanks for the reproduction

Firsting first `next lint` don't work with `overrides` https://github.com/B2o5T/graphql-eslint/issues/988#issuecomment-1081732944, if you want to fix it please open an issue in Next.js repo. Replacing with `eslint .` will make `overrides` config works.

> Running yarn lint will show no errors, however, I'm using a message type in the user.graphql file, which doesn't exist in my graphql schema.

What is your expectation of working if you only extend `schema-recommended` config? Please follow [monorepo example config](https://github.com/B2o5T/graphql-eslint/blob/master/examples/monorepo/.eslintrc.cjs) for your case.

Your config MUST looks like:

```json
{
  "extends": "next/core-web-vitals",
  "overrides": [
    {
      "files": ["*.graphql"],
      "parserOptions": {
        "schema": "./schema.graphql",
        "operations": "./user.graphql"
      }
    },
    {
      "files": "schema.graphql",
      "extends": "plugin:@graphql-eslint/schema-recommended"
    },
    {
      "files": "user.graphql",
      "extends": "plugin:@graphql-eslint/operations-recommended"
    }
  ]
}
```
And I'll get expected output:
```sh
/Users/dimitri/Desktop/graphql-eslint-nextjs/schema.graphql
   1:8   error  Description is required for `scalar Date`                        @graphql-eslint/require-description
   7:6   error  Description is required for `type Query`                         @graphql-eslint/require-description
  15:6   error  Description is required for `enum Role`                          @graphql-eslint/require-description
  20:11  error  Description is required for `interface Node`                     @graphql-eslint/require-description
  24:7   error  Description is required for `union SearchResult`                 @graphql-eslint/require-description
  26:6   error  Description is required for `type User`                          @graphql-eslint/require-description
  28:3   error  Field "username" starts with the name of the parent type "User"  @graphql-eslint/no-typename-prefix
  33:6   error  Description is required for `type Chat`                          @graphql-eslint/require-description
  39:6   error  Description is required for `type ChatMessage`                   @graphql-eslint/require-description

/Users/dimitri/Desktop/graphql-eslint-nextjs/user.graphql
  1:7  error  Operation "message" should be in PascalCase format  @graphql-eslint/naming-convention
  2:3  error  Cannot query field "message" on type "Query"        @graphql-eslint/fields-on-correct-type

✖ 11 problems (11 errors, 0 warnings)
```

I'll close this issue since there is nothing wrong with `graphql-eslint`

**Closed by B2o5T** 2022-06-20 22:36 UTC
