### ISSUE TITLE
Broken autofix for ESLint's `spaced-comment` rule

### ISSUE THREAD

**Issue by shogunsea** [B2o5T/graphql-eslint#1191] opened 2022-10-05 23:30 UTC
**Is your feature request related to a problem? Please describe.**
It looks like the comment node are extracted here: https://github.com/B2o5T/graphql-eslint/blob/4bcee4a7849602076fb9e0d9ab33e78141e20a8e/packages/plugin/src/estree-converter/utils.ts#L109
but since the API conforms to the `SourceLocation` type from estree, there's no actual `comment` field exposed. 

Therefore it's not possible to disable a rule on a per field basis.

**Describe the solution you'd like**
Expose the comment field to the `Node` type:
https://github.com/B2o5T/graphql-eslint/blob/c33bde9c1c5bd8aa780a8ef6c1737eaaaa95f3b0/packages/plugin/src/estree-converter/types.ts#L106-L116

This way we can detect the comment on a field like https://github.com/relayjs/eslint-plugin-relay/blob/main/src/utils.js#L111-L114
which lets us disable a rule on a field level. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by B2o5T** [comment] 2022-10-07 08:53
Hi, can you send code example of 

> Therefore it's not possible to disable a rule on a per field basis.

**Comment by shogunsea** [comment] 2022-10-07 19:01
@B2o5T  hi yes, something like this:
https://github.com/relayjs/eslint-plugin-relay/blob/fcacf1ed69097dd3a47856be8984de45a81c92f7/test/unused-fields.js#L88-L91

**Comment by B2o5T** [comment] 2022-10-09 00:34
the following comment disables report of error on my side
<img width="544" alt="image" src="https://user-images.githubusercontent.com/7361780/194732225-58feb2c5-a216-42ad-9f06-18ff2970faad.png">

**Comment by shogunsea** [comment] 2022-10-09 18:04
@B2o5T that's interesting, I wonder if it's because the file is a JS file and it's the babel parser in play? Could you try to see if the comment works for a `.graphql` file?

**Comment by B2o5T** [comment] 2022-10-09 18:34
I don’t need to test, it works, please create a reproduction of your problem with your configuration with minimal dependencies installed if you need help

**Comment by shogunsea** [comment] 2022-10-10 04:32
@B2o5T ah yeah it actually works. It turns out [this rule](https://eslint.org/docs/latest/rules/spaced-comment) is causing some kind of conflicts with the comment line in my .graphql file, after disabling that rule it's working as expected, I'm guessing it's handled at higher level by eslint instead of needs to be explicitly supported by the parser itself.

**Comment by B2o5T** [comment] 2022-10-11 17:52
@shogunsea I reopened your PR to figure out why there are conflicts with `spaced-comment` rule when I'll have a time

**Comment by taejs** [comment] 2022-11-17 12:27
1.
```graphql
type TEST {
  _id: ID! # eslint-disable-line @graphql-eslint/naming-convention
```

2.
```graphql
type TEST {
  _id: ID! #eslint-disable-line @graphql-eslint/naming-convention
```

The error occurs when comments are written without a space in the schema (Second one)

**Comment by B2o5T** [comment] 2022-12-27 23:44
as @taejs GraphQL-ESLint doesn't have any conflicts with `spaced-comment`, even it works very well with the default ESLint `spaced-comment` rule 😅

closing

**Comment by sharmilajesupaul** [comment] 2023-05-02 17:36
@B2o5T why was this issue closed? we're still seeing a bug where the autofix is broken if you're using spaced-comment with graphql-eslint.

**Comment by dotansimha** [comment] 2023-05-02 18:47
can you please share a reproduction?

**Comment by B2o5T** [comment] 2023-05-03 13:38
@shogunsea https://github.com/eslint/eslint/issues/17145

**Comment by B2o5T** [comment] 2023-05-03 20:10
Since this rule has problems with autofix for `graphql` files and ESLint rejected making this rule `agnostic`:

I suggest either disable it for `*.graphql` files or continuing to use it but without auto-fixing his errors

**Closed by B2o5T** 2023-05-03 20:10 UTC
Labels: invalid
