### ISSUE TITLE
3.11.2: memory issues and Invalid string length

### ISSUE THREAD

**Issue by jlowcs** [B2o5T/graphql-eslint#1175] opened 2022-09-27 11:19 UTC
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on GitHub, Stackblitz or CodeSandbox
     > Please make sure the graphql-eslint version under `package.json` matches yours.
- [ ] 2. A failing test has been provided
- [ ] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

I'm seeing some memory issues since bumping to 3.11.2.

On one repository (CI and locally):
```
<--- Last few GCs --->

[107:0x6a93a00]    37386 ms: Scavenge 2026.1 (2076.3) -> 2021.6 (2077.6) MB, 8.5 / 0.0 ms  (average mu = 0.750, current mu = 0.568) allocation failure; 
[107:0x6a93a00]    37415 ms: Scavenge 2027.4 (2077.9) -> 2023.7 (2079.9) MB, 8.7 / 0.0 ms  (average mu = 0.750, current mu = 0.568) allocation failure; 
[107:0x6a93a00]    37891 ms: Scavenge 2029.5 (2079.9) -> 2025.3 (2097.2) MB, 459.1 / 0.0 ms  (average mu = 0.750, current mu = 0.568) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0xb6dd40 node::Abort() [node]
 2: 0xa7db1c  [node]
 3: 0xd47560 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xd47907 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xf24cc5  [node]
 6: 0xf371ad v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0xf118ae v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0xf12c77 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xef3e4a v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x12b73ef v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x16e9039  [node]
Aborted (core dumped)

Exited with code exit status 134
```

on another, the CI simply kills it after a short while (locally:
```
Killed

Exited with code exit status 137
```

Locally I'm seeing this:
```
Oops! Something went wrong! :(

ESLint: 8.24.0

RangeError: Cannot read config file: /Users/userName/repo/.eslintrc.js
Error: Invalid string length
    at updateOutput (/Users/userName/repo/node_modules/ts-node/src/index.ts:1666:66)
    at Object.compile (/Users/userName/repo/node_modules/ts-node/src/index.ts:1460:20)
    at Module.m._compile (/Users/userName/repo/node_modules/ts-node/src/index.ts:1617:30)
    at Module.m._compile (/Users/userName/repo/node_modules/ts-node/src/index.ts:1618:23)
    at Module.m._compile (/Users/userName/repo/node_modules/ts-node/src/index.ts:1618:23)
    at Module.m._compile (/Users/userName/repo/node_modules/ts-node/src/index.ts:1618:23)
    at Module.m._compile (/Users/userName/repo/node_modules/ts-node/src/index.ts:1618:23)
    at Module.m._compile (/Users/userName/repo/node_modules/ts-node/src/index.ts:1618:23)
    at Module.m._compile (/Users/userName/repo/node_modules/ts-node/src/index.ts:1618:23)
    at Module.m._compile (/Users/userName/repo/node_modules/ts-node/src/index.ts:1618:23)
[...]
```

**To Reproduce**

**Expected behavior**

**Environment:**

- OS: MacOS 12.6
- `@graphql-eslint/eslint-plugin`: 3.11.2
- Node.js: 18.9.1

**Additional context**

**Comment by jlowcs** [comment] 2022-09-27 11:20
If I comment out the `files: ['*.graphql'],` override, and on leave the `processor: '@graphql-eslint/graphql'` in, I'm getting:
```
Error: ESLint configuration of processor in '.eslintrc.js#overrides[0]' is invalid: '@graphql-eslint/graphql' was not found.
```

**Comment by B2o5T** [comment] 2022-09-27 11:56
Hi @jlowcs could you create a reproduction of your problem? This will be helpful for me for debug what is wrong

**Comment by jlowcs** [comment] 2022-09-27 13:28
I wish I easily could, but I have no idea what is causing the issue in our projects (they are both quite big and complex), so I don't know where to start to build a reproduction repo. It's probably gonna take me a while to figure that out (and I'm a bit swamped at the moment).

I'll try to get back to this when I have a moment.

**Comment by B2o5T** [comment] 2022-09-27 13:43
Do you have this error on 3.10.0?
Also since error goes from ts-node try to update it

**Comment by jlowcs** [comment] 2022-09-27 13:50
ts-node is up to date

First error (OoM)
- 3.11.1: different error (`parserOptions.schema` missing when it's there)
- 3.10.7: no error

The second error (Invalid string length)
- 3.11.1: no error
- 3.10.7: no error

**Comment by jlowcs** [comment] 2022-09-28 12:08
On the repository where I was able to bump without error, I ended up having issues with slowness in VSCode when the eslint plugin would run. It would take a few seconds instead of being immediate. So I had the revert back to 3.10.7 there as well.

I strongly suspect some kind of memory leak.

**Comment by B2o5T** [comment] 2022-09-28 17:08
Seems it’s a regression by this update https://github.com/B2o5T/graphql-eslint/pull/1156

Still needs some reproduction to figure out why this happens

**Comment by B2o5T** [comment] 2022-10-08 22:04
Could you test `3.11.3-alpha-20221008220048-6ed3933` and say if your issue was fixed?

**Comment by B2o5T** [comment] 2022-10-10 13:40
should be fixed in `@graphql-eslint/eslint-plugin@3.12.0`

**Closed by B2o5T** 2022-10-10 13:40 UTC
Labels: stage/5-alpha-release-testing, kind/bug

**Comment by jlowcs** [comment] 2022-10-10 13:43
Tested `3.12.0-alpha-20221010131634-608c49a` on 3 projects:
- the one with "JavaScript heap out of memory" => issue is not occurring anymore
- the one with "Cannot read config file" => issue is not occurring anymore
- one with VSCode slowness => issue doesn't seem to be occurring anymore

**Comment by B2o5T** [comment] 2022-10-10 13:46
@jlowcs thank you! 🎉🚀
